### ISSUE TITLE
ARIMA Issue

### ISSUE THREAD

**Issue by indy1345** [biolab/orange3-addons#5]
I get the below error when trying to use the ARIMA timeseries widget:

![image](https://user-images.githubusercontent.com/107656249/174198270-d70bf509-0672-4ea4-ad97-474c9366c9c2.png)

**Comment by janezd** [comment]
Caused by https://github.com/biolab/orange3-timeseries/pull/200, reverted in https://github.com/biolab/orange3-timeseries/pull/207, reapplied in https://github.com/biolab/orange3-timeseries/pull/235 after merging https://github.com/biolab/orange-widget-base/pull/202.

TL;DR: Should work now. :)
